// Per-locale strings for the Sign in / Sign up flow.
// Kept separate from i18n.js so adding a new auth screen doesn't bloat the
// main translations file, and so the auth client component can import a
// small, focused module.

export const AUTH_STRINGS = {
  en: {
    signInTitle: "Sign in",
    signUpTitle: "Create account",
    signInSubtitle: "Sign in to use Ask AI and save your sessions.",
    signUpSubtitle: "Create an account to use Ask AI and save your sessions.",
    emailLabel: "Email address",
    emailPlaceholder: "you@example.com",
    passwordLabel: "Password",
    passwordPlaceholder: "Choose a strong password",
    passwordSignInPlaceholder: "Your password",
    passwordHint: "At least 8 characters.",
    signInBtn: "Sign in",
    signUpBtn: "Create account",
    sendMagicLinkBtn: "Email me a magic link",
    googleBtn: "Continue with Google",
    or: "or",
    backToSignIn: "Back to sign in",
    needAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    forgotPassword: "Forgot your password?",
    sendingLink: "Sending link…",
    linkSent: "Check your email — we just sent you a sign-in link.",
    signingIn: "Signing in…",
    creatingAccount: "Creating account…",
    confirmEmailSent: "We sent a confirmation link to your email. Open it to finish setting up your account.",
    invalidCredentials: "Invalid email or password.",
    rateLimited: "Too many attempts. Please wait a moment and try again.",
    genericError: "Something went wrong. Please try again.",
    signOut: "Sign out",
    signedInAs: "Signed in as",
    yourAccount: "Your account"
  },
  ar: {
    signInTitle: "تسجيل الدخول",
    signUpTitle: "إنشاء حساب",
    signInSubtitle: "سجّل الدخول لاستخدام Ask AI وحفظ جلساتك.",
    signUpSubtitle: "أنشئ حساباً لاستخدام Ask AI وحفظ جلساتك.",
    emailLabel: "البريد الإلكتروني",
    emailPlaceholder: "you@example.com",
    passwordLabel: "كلمة المرور",
    passwordPlaceholder: "اختر كلمة مرور قوية",
    passwordSignInPlaceholder: "كلمة المرور",
    passwordHint: "8 أحرف على الأقل.",
    signInBtn: "تسجيل الدخول",
    signUpBtn: "إنشاء حساب",
    sendMagicLinkBtn: "أرسل لي رابط دخول",
    googleBtn: "المتابعة عبر Google",
    or: "أو",
    backToSignIn: "العودة لتسجيل الدخول",
    needAccount: "ليس لديك حساب؟",
    haveAccount: "لديك حساب بالفعل؟",
    forgotPassword: "نسيت كلمة المرور؟",
    sendingLink: "يتم إرسال الرابط…",
    linkSent: "تحقّق من بريدك — أرسلنا لك رابط دخول.",
    signingIn: "جاري تسجيل الدخول…",
    creatingAccount: "جاري إنشاء الحساب…",
    confirmEmailSent: "أرسلنا رابط تأكيد إلى بريدك. افتحه لإكمال إنشاء حسابك.",
    invalidCredentials: "البريد أو كلمة المرور غير صحيحة.",
    rateLimited: "محاولات كثيرة. انتظر قليلاً وحاول مرة أخرى.",
    genericError: "حدث خطأ. حاول مرة أخرى.",
    signOut: "تسجيل الخروج",
    signedInAs: "تم تسجيل الدخول باسم",
    yourAccount: "حسابك"
  },
  tr: {
    signInTitle: "Giriş yap",
    signUpTitle: "Hesap oluştur",
    signInSubtitle: "Ask AI'yı kullanmak ve oturumlarınızı kaydetmek için giriş yapın.",
    signUpSubtitle: "Ask AI'yı kullanmak ve oturumlarınızı kaydetmek için bir hesap oluşturun.",
    emailLabel: "E-posta adresi",
    emailPlaceholder: "ornek@email.com",
    passwordLabel: "Şifre",
    passwordPlaceholder: "Güçlü bir şifre seçin",
    passwordSignInPlaceholder: "Şifreniz",
    passwordHint: "En az 8 karakter.",
    signInBtn: "Giriş yap",
    signUpBtn: "Hesap oluştur",
    sendMagicLinkBtn: "Bana sihirli bağlantı gönder",
    googleBtn: "Google ile devam et",
    or: "veya",
    backToSignIn: "Girişe dön",
    needAccount: "Hesabınız yok mu?",
    haveAccount: "Zaten hesabınız var mı?",
    forgotPassword: "Şifrenizi mi unuttunuz?",
    sendingLink: "Bağlantı gönderiliyor…",
    linkSent: "E-postanızı kontrol edin — size bir giriş bağlantısı gönderdik.",
    signingIn: "Giriş yapılıyor…",
    creatingAccount: "Hesap oluşturuluyor…",
    confirmEmailSent: "E-postanıza bir onay bağlantısı gönderdik. Hesabınızı kurmayı tamamlamak için açın.",
    invalidCredentials: "Geçersiz e-posta veya şifre.",
    rateLimited: "Çok fazla deneme. Lütfen biraz bekleyin ve tekrar deneyin.",
    genericError: "Bir şeyler ters gitti. Lütfen tekrar deneyin.",
    signOut: "Çıkış yap",
    signedInAs: "Giriş yapan",
    yourAccount: "Hesabınız"
  }
};

export function pickAuthStrings(locale) {
  const k = String(locale || "en").toLowerCase();
  if (k === "ar" || k === "tr") return AUTH_STRINGS[k];
  return AUTH_STRINGS.en;
}
